# This workflow needs to be run on demand
# It will search for all repositories containing the provided action and open pull requests

name: Update workflow from org template

on:
  workflow_dispatch:
    inputs:
      name:
        description: "The workflow to update (with .yml)"
        required: true
        default: "node.yml"

jobs:
  dispatchWorkflow:
    runs-on: ubuntu-latest
    
    steps:
      # Create check run
      - name: Search repositories using the ${{ github.event.inputs.name }} workflow
        uses: octokit/request-action@v2.x
        id: search-repos
        with:
          route: GET /search/code/
          q: "org:${{ github.repository_owner }} path:/.github/workflows filename:${{ github.event.inputs.name }}"
          per_page: 100
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Processing repositories list
        uses: edwardgeorge/jq-action@v1
        id: repos-list
        with:
          input: ${{ steps.search-repos.outputs.data }}
          script: ".items | .[] | .repository.name"

      - name: List repositories
        run: echo ${{ steps.repos-list.outputs.output }}
