# This workflow needs to be run on demand
# It will search for all repositories containing the provided
# action and open pull requests if necessary.

name: Update workflow from org template

on:
  workflow_dispatch:
    inputs:
      name:
        description: "The workflow to update (with .yml)"
        required: true
        default: "node.yml"

jobs:
  repositories:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.search-repos.outputs.matrix }}
      
    name: repositories search (${{ github.event.inputs.name }})

    steps:
      - name: Check actor permission
        uses: skjnldsv/check-actor-permission@v2
        with:
          require: admin

      - name: Search repositories using the ${{ github.event.inputs.name }} workflow
        id: search-repos
        # This is a simple curl to fetch the list of repos containing a file and extracting the repo names
        run: |
          REPOS=$(curl -H "Accept: application/vnd.github.v3+json" "https://api.github.com/search/code?q=org%3A${{ github.repository_owner }}%20path%3A.github%2Fworkflows%20filename%3A${{ github.event.inputs.name }}&per_page=100" | jq -c '.items | map(.repository.name) | unique')
          echo "::set-output name=matrix::$REPOS"

  dispatch:
    runs-on: ubuntu-latest
    needs: repositories

    strategy:
      fail-fast: false
      matrix:
        repositories: ${{ fromJSON(needs.repositories.outputs.matrix) }}

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          path: source

      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          path: target
          repository: ${{ github.repository_owner }}/${{ matrix.repositories }}

      - name: Copy workflow
        run: cp ./source/workflow-templates/${{ github.event.inputs.name }} ./target/.github/workflows

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          body: Automated update of the ${{ github.event.inputs.name }} workflow from https://github.com/${{ github.repository }}
          branch: feat/workflow-auto-update-${{ github.event.inputs.name }}
          commit-message: Updating ${{ github.event.inputs.name }} workflow from template
          committer: Nextcloud bot <bot@nextcloud.com>
          author: Nextcloud bot <bot@nextcloud.com>
          path: target
          signoff: true
          title: Updating ${{ github.event.inputs.name }} workflow from template 
          labels: dependencies
          token: ${{ secrets.TEMPLATE_WORKFLOW_DISPATCH_PAT }}
