name: Lint

on: pull_request

jobs:
  yaml-lint:
    runs-on: ubuntu-latest

    name: yaml

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Github action templates lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: workflow-templates
          config_data: |
            line-length: warning
