name: Lint

on: pull_request

jobs:
  yaml-lint:
    runs-on: ubuntu-latest

    name: yaml

    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Github action templates lint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3
        with:
          file_or_dir: workflow-templates
          config_data: |
            line-length: warning
